---
title: "R Notebook"
output: html_notebook
---
```{r}
data<-trade_zone_table


```

```{r}
Countries<-c("Algeria",
"Angola",
"Benin",
"Botswana",
"Burkina Faso",
'Burundi',
"Cabo Verde",
"Cameroon",
'Central African Republic',
"Chad",
"Comoros",
"Cote d'Ivoire",
'Democratic Republic of the Congo',
"Djibouti",
"Egypt",
'Equatorial Guinea',
"Eritrea",
"Ethiopia",
"Gabon",
"Gambia",
"Ghana",
"Guinea",
"Guinea-Bissau",
"Kenya",
"Lesotho",
"Liberia",
"Libya",
"Madagascar",
"Malawi",
"Mali",
"Mauritania",
"Mauritius",
"Morocco",
"Mozambique",
"Namibia",
"Niger",
"Nigeria",
'Republic of the Congo',
"Rwanda",
'Sao Tome and Principe',
'Senegal',
'Seychelles',
'Sierra Leone',
'Somalia',
'South Africa',
'South Sudan',
'Sudan',
'Swaziland',
'Tanzania',
'Togo',
'Tunisia',
'Uganda',
'Zambia',
'Zimbabwe'
)


```
```{r}
library(dplyr)
data[is.na(data)]<-0
data
```


```{r}


# Country_1 <-c(1,1,0,0)
# Country_2 <-c(1,0,1,0)
# Country_3 <-c(1,0,1,0)
# Country_4 <-c(0,1,0,1)
# Country_5 <-c(0,0,1,1)
# 
# Countries<-c("Country_1","Country_2","Country_3","Country_4","Country_5")
# Zone_1<-c(1,1,1,0,0)
# Zone_2<-c(1,0,0,1,0)
# Zone_3<-c(0,1,1,0,1)
# Zone_4<-c(0,0,0,1,1)
library(tidygraph)

data<-as.matrix(data)
rownames(data) <- paste(Countries)

as_tbl_graph(graph.incidence(data))


```


```{r}
library(ggraph)
as_tbl_graph(graph.incidence(data)) %>% 
  ggraph()+
  geom_node_point(aes(shape = type, size = 20), show.legend = F)+
  geom_node_text(aes(label = name), colour = 'black', vjust = 4)+
  geom_edge_link()+
  theme_graph()
```

```{r}
data_project<- bipartite.projection(graph.incidence(data)) 
data_project

as_tbl_graph(data_project$proj1)
country_data<-as_tbl_graph(data_project$proj1)
```

```{r}
as_tbl_graph(data_project$proj1) %>% 
  ggraph()+
  geom_node_point(aes(size = 20), show.legend = F)+
  geom_node_text(aes(label = name), colour = 'black', vjust = 4)+
  geom_edge_link()+
  theme_graph()


```

```{r}
# random_graph <- sample_gnp(n = 100, 0.2)
graph_data<-as_tbl_graph(data)

# 
# GLI_rg <- as_tbl_graph(country_data) %>%
#   mutate(size = graph_order(),
#          edges = graph_size(),
#          density = edge_density(country_data),
#          average_distance = graph_mean_dist(),
#          trans = transitivity(country_data, type = "global")
#   ) %>%
#   as.data.frame()
# 
# GLI_rg

info<-country_data%>%
  activate(nodes)%>%
  mutate(betweenness = centrality_betweenness(normalized = TRUE),
         closeness = centrality_closeness(normalized = TRUE),
         transitivity = transitivity(country_data,type = "local"),
         degree = degree(country_data))%>%
  select(name,betweenness,closeness,transitivity,degree)%>%
  as.data.frame()
info




```
```{r}
library(ggplot2)


data.frame(info)%>%
  ggplot(aes(x=betweenness,y=closeness, label=name))+
  geom_point()+geom_text()+scale_x_log10()+geom_smooth(method="lm",size = 0.5)+ylab("Closeness Centrality")+xlab("betweenness")

```
```{r}
#define variables to all to allinfo variable, ie gdp_data and mortality stats



allinfo$GDP.growth.rate<-as.numeric(allinfo$GDP.growth.rate)



```


```{r}

data.frame(allinfo)%>%
  ggplot(aes(x=GDP.perCapita,y=closeness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(x=GDP.perCapita,y=betweenness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(y=GDP.perCapita,x=degree, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

```


```{r}

data.frame(allinfo)%>%
  ggplot(aes(x=African.rank,y=closeness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()+xlab("African.rank")+ylab("closeness")

data.frame(allinfo)%>%
  ggplot(aes(x=African.rank,y=betweenness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()+xlab("African.rank")+ylab("betweenness")

data.frame(allinfo)%>%
  ggplot(aes(x=African.rank,y=degree, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()


data.frame(allinfo)%>%
  ggplot(aes(x=degree,y=African.rank, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()


```
```{r fig.width=12, fig.height=12}
data.frame(allinfo)%>%
  ggplot(aes(x=World.rank,y=closeness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()+xlab("World.rank")+ylab("closeness")

data.frame(allinfo)%>%
  ggplot(aes(x=World.rank,y=betweenness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()+xlab("World.rank")+ylab("betweenness")

data.frame(allinfo)%>%
  ggplot(aes(x=World.rank,y=degree, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()+xlab("World.rank")+ylab("degree")

data.frame(allinfo)%>%
  ggplot(aes(x=degree,y=World.rank, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()+ylab("World.rank")+xlab("degree")

```



```{r fig.width=12, fig.height=12}
data.frame(allinfo)%>%
  ggplot(aes(x=GDP.from.agriculture,y=closeness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()+xlab("GDP.from.agriculture")+ylab("closeness")

data.frame(allinfo)%>%
  ggplot(aes(x=GDP.from.agriculture,y=betweenness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()+xlab("GDP.from.agriculture")+ylab("betweenness")

data.frame(allinfo)%>%
  ggplot(aes(x=GDP.from.agriculture,y=degree, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()+xlab("GDP.from.agriculture")+ylab("degree")


data.frame(allinfo)%>%
  ggplot(aes(x=closeness,y=GDP.from.agriculture, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(x=betweenness,y=GDP.from.agriculture, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(x=degree,y=GDP.from.agriculture, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()
```


```{r fig.width=12, fig.height=12}
data.frame(allinfo)%>%
  ggplot(aes(x=GDP..industry,y=closeness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()+xlab("GDP..industry")+ylab("closeness")

data.frame(allinfo)%>%
  ggplot(aes(x=GDP..industry,y=betweenness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()+xlab("GDP..industry")+ylab("betweenness")

data.frame(allinfo)%>%
  ggplot(aes(x=GDP..industry,y=degree, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()+xlab("GDP..industry")+ylab("degree")

data.frame(allinfo)%>%
  ggplot(aes(x=closeness,y=GDP..industry, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(x=betweenness,y=GDP..industry, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(x=degree,y=GDP..industry, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()
```


```{r fig.width=12, fig.height=12}
data.frame(allinfo)%>%
  ggplot(aes(x=GDP.services,y=closeness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()+xlab("GDP.services")+ylab("closeness")

data.frame(allinfo)%>%
  ggplot(aes(x=GDP.services,y=betweenness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()+xlab("GDP.services")+ylab("betweenness")

data.frame(allinfo)%>%
  ggplot(aes(x=GDP.services,y=degree, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()+xlab("GDP.services")+ylab("degree")

```

```{r fig.width=12, fig.height=12}
data.frame(allinfo)%>%
  ggplot(aes(x=GDP.estimates,y=closeness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()+xlab("GDP.estimates")+ylab("closeness")

data.frame(allinfo)%>%
  ggplot(aes(x=GDP.estimates,y=betweenness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()+xlab("GDP.estimates")+ylab("betweenness")

data.frame(allinfo)%>%
  ggplot(aes(x=GDP.estimates,y=degree, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()+xlab("GDP.estimates")+ylab("degree")

```
```{r fig.width=12, fig.height=12}
data.frame(allinfo)%>%
  ggplot(aes(x=GDP.growth.rate,y=closeness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()+xlab("GDP.growth.rate")+ylab("closeness")

data.frame(allinfo)%>%
  ggplot(aes(x=GDP.growth.rate,y=betweenness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()+xlab("GDP.growth.rate")+ylab("betweenness")

data.frame(allinfo)%>%
  ggplot(aes(x=GDP.growth.rate,y=degree, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()+xlab("GDP.growth.rate")+ylab("degree")
```

```{r}
ggplot(data.frame(allinfo),aes(x=name,y=closeness))+geom_bar(stat="identity")+theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplot(data.frame(allinfo),aes(x=name,y=betweenness))+geom_bar(stat="identity")+theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplot(data.frame(allinfo),aes(x=name,y=degree))+geom_bar(stat="identity")+theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r fig.width=12, fig.height=12}
data.frame(allinfo)%>%
  ggplot(aes(x=closeness,y=LifeExp, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(x=betweenness,y=LifeExp, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(x=degree,y=LifeExp, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

```
```{r fig.width=12, fig.height=12}
data.frame(allinfo)%>%
  ggplot(aes(y=Neonatel,x=closeness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(y=Neonatel,x=betweenness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(y=Neonatel,x=degree, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()
```


```{r fig.width=12, fig.height=12}
data.frame(allinfo)%>%
  ggplot(aes(x=Infant_Mortality,y=closeness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(x=Infant_Mortality,y=betweenness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(x=Infant_Mortality,y=degree, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()


data.frame(allinfo)%>%
  ggplot(aes(y=Infant_Mortality,x=closeness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(y=Infant_Mortality,x=betweenness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(y=Infant_Mortality,x=degree, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()
```

```{r fig.width=12, fig.height=12}
data.frame(allinfo)%>%
  ggplot(aes(x=under_5,y=closeness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(x=under_5,y=betweenness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(x=under_5,y=degree, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()


data.frame(allinfo)%>%
  ggplot(aes(y=under_5,x=closeness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(y=under_5,x=betweenness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(y=under_5,x=degree, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()
```



```{r fig.width=12, fig.height=12}
data.frame(allinfo)%>%
  ggplot(aes(x=Male_adult_mortality,y=closeness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(x=Male_adult_mortality,y=betweenness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(x=Male_adult_mortality,y=degree, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()


data.frame(allinfo)%>%
  ggplot(aes(y=Male_adult_mortality,x=closeness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(y=Male_adult_mortality,x=betweenness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(y=Male_adult_mortality,x=degree, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()
```

```{r fig.width=12, fig.height=12}
data.frame(allinfo)%>%
  ggplot(aes(x=female_adult_mortality,y=closeness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(x=female_adult_mortality,y=betweenness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(x=female_adult_mortality,y=degree, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()


data.frame(allinfo)%>%
  ggplot(aes(y=female_adult_mortality,x=closeness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(y=female_adult_mortality,x=betweenness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(y=female_adult_mortality,x=degree, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()
```
```{r fig.width=12, fig.height=12}

data.frame(allinfo)%>%
  ggplot(aes(x=Infant_Mortality,y=closeness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(x=Infant_Mortality,y=betweenness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(x=Infant_Mortality,y=degree, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()


data.frame(allinfo)%>%
  ggplot(aes(y=Infant_Mortality,x=closeness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(y=Infant_Mortality,x=betweenness, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

data.frame(allinfo)%>%
  ggplot(aes(y=Infant_Mortality,x=degree, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()
```

```{r fig.width=12, fig.height=12}

data.frame(allinfo)%>%
  ggplot(aes(y=closeness,x=degree, label=name))+
  geom_point()+geom_text()+geom_smooth(method="lm",size = 0.5)+scale_x_log10()+scale_y_log10()

```

```{r fig.width=8, fig.height=8}
allinfo<-data.frame(c(info, gdp_data, mortal))
trade_info <-data.frame(allinfo, african_trade_items)

data.frame(trade_info) %>% 
  ggplot(aes(x=resource, y=GDP.perCapita, label=name.1, color=resource)) +
  geom_point() +
  geom_text() +
  geom_smooth(method="lm", size=0.5) +
  ylab("GDP") + xlab("Country") +
  labs(title="Ordered Bar Chart", 
  subtitle="Make Vs Avg. Mileage", 
  caption="source: mpg") + 
  theme(axis.text.x = element_text(angle=65, vjust=0.6))

```

```{r fig.width=20, fig.height=10 }
temp <- trade_info %>%
  group_by(name.1) %>%
  mutate(GDP_industry = GDP.perCapita*(GDP..industry/100),
         GDP_agri = GDP.perCapita*(GDP.from.agriculture/100),
         GDP_services = GDP.perCapita*(GDP.services/100)) %>%
  select(GDP.perCapita,GDP_industry,GDP_agri,GDP_services)

data.frame(trade_info) %>% 
  ggplot(aes(x=name.1, y=GDP.perCapita, label=name.1, fill=resource)) +
  facet_wrap(~resource) +
  geom_col() +
  geom_text() +
  geom_smooth(method="lm", size=0.5) +
  ylab("GDP") + xlab("Country") +
  labs(title="Ordered Bar Chart", 
  subtitle="Make Vs Avg. Mileage", 
  caption="source: mpg") + 
  theme(axis.text.x = element_text(angle=65, vjust=0.6))
```